{
 "title": "PCP Redis: Host Overview Copy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "pcp-redis-datasource" },
   { "name": "host", "query": "label_values(hostname)" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel.all.load{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem.util.free{hostname == \"$host\"}",
     "legendFormat": "$metric"
    },
    {
     "expr": "mem.util.cached{hostname == \"$host\"}",
     "legendFormat": "$metric"
    },
    {
     "expr": "mem.physmem{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Per-CPU busy (User)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kernel.percpu.cpu.user{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Per-CPU busy (Sys)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kernel.percpu.cpu.sys{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Context switches per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kernel.all.pswitch{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "Runnable",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel.all.runnable{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem.util.used{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "Cached",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem.util.cached{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "Free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem.util.free{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "Page fault rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mem.vmstat.pgfault{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "Hard fault rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mem.vmstat.pgmajfault{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Throughput (In)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "network.interface.in.bytes{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Network Throughput (Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "network.interface.out.bytes{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Network Drops (In)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.interface.in.drops{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Network Drops (Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.interface.out.drops{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Network Packets (In)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.interface.in.packets{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "Network Packets (Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.interface.out.packets{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TCP Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network.tcp.timeouts{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "TCP Listen Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.tcp.listendrops{hostname == \"$host\"}",
     "legendFormat": "$metric"
    },
    {
     "expr": "network.tcp.listenoverflows{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "TCP Retransmits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "network.tcp.retranssegs{hostname == \"$host\"}",
     "legendFormat": "$metric"
    },
    {
     "expr": "network.tcp.fastretrans{hostname == \"$host\"}",
     "legendFormat": "$metric"
    },
    {
     "expr": "network.tcp.slowstartretrans{hostname == \"$host\"}",
     "legendFormat": "$metric"
    },
    {
     "expr": "network.tcp.synretrans{hostname == \"$host\"}",
     "legendFormat": "$metric"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "disk.dev.read_rawactive{hostname == \"$host\"}",
     "legendFormat": "read $instance"
    },
    {
     "expr": "disk.dev.write_rawactive{hostname == \"$host\"}",
     "legendFormat": "write $instance"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "disk.dev.read{hostname == \"$host\"}",
     "legendFormat": "read $instance"
    },
    {
     "expr": "disk.dev.write{hostname == \"$host\"}",
     "legendFormat": "write $instance"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "KiBs" }
   ],
   "targets": [
    {
     "expr": "disk.dev.read_bytes{hostname == \"$host\"}",
     "legendFormat": "read $instance"
    },
    {
     "expr": "disk.dev.write_bytes{hostname == \"$host\"}",
     "legendFormat": "write $instance"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "disk.dev.avactive{hostname == \"$host\"}",
     "legendFormat": "$instance"
    }
   ]
  }
 ]
}