---

- hosts: package_cache
  roles:
    - package_cache

- hosts: all
  roles:
   - common

- hosts:
    - proxy
    - storage
  roles:
    - swift_common

- hosts: authentication
  roles:
   - authentication

- hosts: proxy
  roles:
   - proxy

# Using serial because of delegate_to in the playbook
- hosts: storage
  #serial: 1
  roles:
    - storage

#
# These are not so much roles as starting services
# though also includes distributing the ring files
# 

- hosts: proxy
  tasks:
  - include: start_proxy.yml

- hosts: storage
  tasks:
  - include: start_storage.yml
  