---

- hosts: package_cache
  roles:
    - package_cache

- hosts: all
  roles:
   - common

- hosts:
    - proxy
    - storage
  roles:
    - swift_common

- hosts: authentication
  roles:
   - authentication

- hosts: proxy
  roles:
   - proxy

- hosts: storage
  roles:
    - storage

- hosts: proxy
  roles:
    - proxy_startup

- hosts: storage
  roles:
    - storage_startup