---

#
# Install swift proxy
# 

- name: install required packages for swift proxy
  apt: pkg=$item state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - swift-proxy 
    - memcached 
    - python-keystoneclient 
    - python-swiftclient 
    - swift-plugin-s3

# XXX Fix key info XXX
- name: create self-signed ssl key 
  #command: chdir=/etc/swift openssl req -new -x509 -nodes -out cert.crt -keyout cert.key
  command: openssl req -new -nodes -x509 -subj "/C=CA/ST=Alberta/L=Edmonton/O=Swift/CN=Example.com" -days 3650 -keyout /etc/swift/cert.key -out /etc/swift/cert.crt -extensions v3_ca creates=/etc/swift/cert.crt

# Create an adminrc file to easily source for testing
- name: create an adminrc file to easily source for testin authentiction
  template: src=adminrc.j2 dest=/root/adminrc

- name: create a swiftrc file to easily source for testin authentiction
  template: src=swiftrc.j2 dest=/root/swiftrc

- name: tell memcached to listen on ip
  lineinfile: dest=/etc/memcached.conf regexp="^-l" line='-l {{ inventory_hostname }}'
  notify: restart memcached

# XXX 
- name: make sure memcached is running
  service: name=memcached state=running

# swift-proxy logs say mode should be 0700
- name: ensure permissions on /var/cache/swift
  file: path=/var/cache/swift state=directory group=swift owner=swift mode=0700

- name: copy over proxy-server.conf
  template: src=proxy-server.conf.j2 dest=/etc/swift/proxy-server.conf owner=swift group=swift mode=0640

- name: check if /etc/swift/*.builder files already exist
  command: find /etc/swift/object.builder
  register: builders
  ignore_errors: True

# XXX how to see if this needs to be run? XXX
- name: run swift-ring-builder for accounts, containers, and objects
  command: chdir=/etc/swift creates=/etc/swift/{{ item }}.ring.gz swift-ring-builder {{ item }}.builder create {{ partition_power }} 3 1   
  with_items:
    - account
    - container
    - object
  when: builders.rc > 0

