---

- name: install required proxy packages
  shell: |
    dnf update -y
    dnf config-manager --enable crb
    dnf install -y centos-release-openstack-zed
    setenforce 0
    dnf update -y
    dnf install -y openstack-swift rsync
    pip install python-swiftclient

