---

- name: install required packages for lxc
  apt: name={{item}} state=installed update_cache=yes cache_valid_time=3600
  with_items:
  - lxc

- name: copy lxc.conf from template
  template: src=lxc.conf.j2 dest=/etc/lxc/lxc.conf owner=root group=root mode=0644

# XXX FIX ME IP XXX
- name: set mirror in /etc/default/lxc
  lineinfile: dest=/etc/default/lxc regexp='^#MIRROR=' line='MIRROR=http://192.168.100.20:3142/archive.ubuntu.com/ubuntu'

- name: create swift lxc containers
  command: creates=/var/lib/lxc/{{ item }} lxc-create -n {{ item }} -t ubuntu 
  with_items:
  - swift-proxy-01
  - swift-storage-01
  - swift-storage-02
  - swift-storage-03
#  - swift-storage-04
#  - swift-storage-05
#  - swift-storage-06

- name: create networking configuration files for each lxc containers
  template: src=interfaces.j2 dest=/var/lib/lxc/{{item.lxc_hostname}}/rootfs/etc/network/interfaces
  with_items:
  - { ip: '100', lxc_hostname: 'swift-proxy-01' }
  - { ip: '200', lxc_hostname: 'swift-storage-01' }
  - { ip: '201', lxc_hostname: 'swift-storage-02' }
  - { ip: '202', lxc_hostname: 'swift-storage-03' }