# XXX shoudl be using apt_key here I think instead of ubuntu-cloud-keyring XX
- name: install required packages to add havana repository
  apt: name=$item state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - ubuntu-cloud-keyring
    - python-pycurl

# XXX Not working; using ubuntu-cloud-keyring package instead
#- name: install havana apt key
#  apt_key: url=http://ubuntu-cloud.archive.canonical.com/ubuntu/dists/precise-updates/havana/Release.gpg 

- name: install havana apt repository
  apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/havana main' state=present

- name: update apt 
  command: apt-get update