---

#
# Test connectivity
#

- name: Test internet connectivity for each host
  command: ping -c 1 -w 1 google.com

#
# NTP
#

- name: install ntp package
  apt: pkg=ntp state=installed

- name: set timezone to {{timezone_area}}/{timezone_city}
  template: src=timezone.j2 dest=/etc/timezone owner=root group=root mode=0644
  register: timezone

- name: setup timezone link
  shell: ln -sf /usr/share/zoneinfo/{{timezone_area}}/{{timezone_city}} /etc/localtime
  when: timezone.changed

#- name: reconfigure tzdata
#  command: dpkg-reconfigure --frontend noninteractive tzdata
#  when: timezone.changed

- name: stop ntpd to run ntpdate
  service: name=ntp state=stopped
  when: timezone.changed

- name: set time with ntpdate
  command: "ntpdate -s ntp.ubuntu.com"
  when: timezone.changed

- name: start ntpd
  service: name=ntp state=running enabled=yes
  when: timezone.changed

#
# Package cache
#

- name: setup apt-cacher-ng proxy
  template: src=01proxy.j2 dest=/etc/apt/apt.conf.d/01proxy

# XXX should be using apt_key here I think instead of ubuntu-cloud-keyring XXX
- name: install required packages to add havana repository
  apt: name=$item state=installed update_cache=yes #cache_valid_time=3600
  with_items:
    - ubuntu-cloud-keyring
    - python-pycurl

# XXX Not working; using ubuntu-cloud-keyring package instead
#- name: install havana apt key
#  apt_key: url=http://ubuntu-cloud.archive.canonical.com/ubuntu/dists/precise-updates/havana/Release.gpg 

- name: install havana apt repository
  apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu precise-updates/havana main' state=present
  register: new_repo

- name: update apt 
  command: apt-get update
  when: new_repo.changed

