---

#- name: configure proxy cache server for yum
#  lineinfile: dest=/etc/yum.conf line="proxy=http://{{ package_cache_server }}:3128" insertafter="^[main]"

# XXX Better way to remove this plugin? XXX
- name: remove fastestmirror plugin
  file: path=/etc/yum/pluginconf.d/fastestmirror.conf state=absent

- name: remove old repofiles
  command: rm -f /etc/yam.repo.d/rhos-release*

- name: Install Openstack packages
  shell: |
    sudo yum install -y centos-release-openstack-victoria openstack-selinux;
    sudo yum config-manager --set-enabled powertools;
    sudo yum upgrade;
    pip3 install openstackclient
  when: ansible_distribution == 'CentOS'

# This breaks yum, we don't want to do this.
# - name: copy over new CentOS-Base.repo file
#   copy: src=CentOS-Base.repo dest=/etc/yum.repos.d/CentOS-Base.repo
#   notify:
#     - yum makecache
#   when: ansible_distribution == 'CentOS'
