---

- name: restart mysql
  service: name=mysql state=restarted

- name: restart keystone
  service: name=keystone state=restarted

- name: copy over proxy-server.conf
  template: src=proxy-server.conf.j2 dest=/etc/swift/proxy-server.conf